#====================================================
# TingoBingo Makefile
#====================================================

CXX = g++

CXXFLAGS = -g -Wall -Wextra -std=c++23 -Iinclude -MMD -MP

LDFLAGS = -lraylib -lopengl32 -lgdi32 -lwinmm

TARGET = build/TingoBingo.exe

#----------------------------------------------------
# Source files
#----------------------------------------------------

SOURCES = $(wildcard src/*.cpp) \
          $(wildcard src/head/*.cpp) \
          $(wildcard src/body/*.cpp)

#----------------------------------------------------
# Object files
#----------------------------------------------------

OBJECTS = $(patsubst src/%.cpp,build/%.o,$(SOURCES))

#----------------------------------------------------
# Dependency files generated by GCC
#----------------------------------------------------

DEPENDS = $(OBJECTS:.o=.d)

#----------------------------------------------------
# Default target
#----------------------------------------------------

all: $(TARGET)

#----------------------------------------------------
# Link executable
#----------------------------------------------------

$(TARGET): $(OBJECTS)
	@echo "Linking TingoBingo..."
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS)

#----------------------------------------------------
# Compile source files
#----------------------------------------------------

build/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) -c $< -o $@

#----------------------------------------------------
# Include automatically generated dependencies
#----------------------------------------------------

-include $(DEPENDS)

#----------------------------------------------------
# Clean build
#----------------------------------------------------

clean:
	rm -f $(OBJECTS)
	rm -f $(DEPENDS)
	rm -f $(TARGET)

#----------------------------------------------------
# Rebuild everything
#----------------------------------------------------

rebuild: clean all