//====================================================
// Speech.cpp
//
// Generates speech audio using Piper.
//
// Text is passed to the Piper command-line tool,
// which creates a WAV file that can later be played
// by the game.
//====================================================

#include "Speech.h"

#include <cstdlib>
#include <iostream>
#include "windows.h"

// Convert text into a spoken WAV file using Piper and ffmpeg for effects.
void Speech::Speak(const std::string& text)
{
    // Generate the clean Alan voice.
    std::string command =
        "echo \"" + text + "\" | "
        "\"tools\\piper\\piper.exe\" "
        "--model \"tools\\piper\\en_GB-alan-medium.onnx\" "
        "--output_file \"assets\\audio\\voice\\speech_raw.wav\"";

    system(command.c_str());

    // Windows structures used to configure and control the
    // FFmpeg process that we are about to launch.

    // Stores information used to configure the new process.
    STARTUPINFOA si{};

    // Receives information about the newly created process.
    PROCESS_INFORMATION pi{};

    // Tell Windows how large the STARTUPINFO structure is.
    si.cb = sizeof(si);

    // Build the command line used to launch FFmpeg.
    //
    // FFmpeg takes the clean WAV generated by Piper,
    // applies the selected audio effect, and writes
    // the processed voice to speech.wav.
    //"-af \"EFFECT HERE\" " is the effect command
    std::string commandLine =
        "\"C:\\dev\\raylib-projects\\TingoBingo_1.0\\tools\\ffmpeg\\bin\\ffmpeg.exe\" "
        "-y "
        "-i \"C:\\dev\\raylib-projects\\TingoBingo_1.0\\assets\\audio\\voice\\speech_raw.wav\" "
        "-af \"aecho=0.8:0.88:60:0.25,"
        "highpass=f=250,"
        "lowpass=f=3500,"
        "acrusher=bits=12:mix=0.15\" "
        "\"C:\\dev\\raylib-projects\\TingoBingo_1.0\\assets\\audio\\voice\\speech.wav\"";

    // Launch FFmpeg as a separate Windows process.
    if (CreateProcessA(
            nullptr,          // Application name (provided in commandLine)
            commandLine.data(), // Command line to execute
            nullptr,          // Default process security attributes
            nullptr,          // Default thread security attributes
            FALSE,            // Do not inherit handles
            CREATE_NO_WINDOW,  // Run FFmpeg without opening a console window
            nullptr,          // Use the parent's environment
            nullptr,          // Use the parent's working directory
            &si,              // Startup information
            &pi))              // Receives information about the new process
    {
        // Wait for FFmpeg to finish processing the audio.
        // This ensures speech.wav is ready before the game
        // attempts to load it.
        WaitForSingleObject(pi.hProcess, INFINITE);

        // Release the Windows handles associated with
        // the FFmpeg process and its main thread.
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);

        // Report that FFmpeg finished.
        std::cout << "FFmpeg completed successfully.\n";
    }
    else
    {
        // FFmpeg could not be launched.
        // GetLastError() provides the Windows error code
        // explaining why CreateProcessA failed.
        std::cout << "Failed to launch FFmpeg. Error: "
                  << GetLastError() << "\n";
    }
}